apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-tidb-namespace.yaml
- 01-tc-a.yaml
- 02-tc-b.yaml
- 03-coredns-nlb.yaml
- 10-tiproxy-system-namespace.yaml
- 11-tiproxy-manager-rbac.yaml
- 12-tiproxy-manager-aws-creds-secret.example.yaml
- 13-tiproxy-manager-deployment.yaml
- 20-tiproxy-machinegroup-and-ports.yaml
- 21-tidb-resource-links.yaml
- 30-seed-tc-a-job.yaml
- 31-seed-tc-b-job.yaml
- 32-mysql-check-pod.yaml
