apiVersion: tiproxy.pingcap.com/v1alpha1
kind: TiDBResourcePoolLink
metadata:
  name: demo-link
  namespace: default
spec:
  machineGroupRef:
    name: demo
  clusterName: demo-cluster
  routeNamespace: demo
  frontendUser: demo_user
  pdAddresses:
  - 10.0.0.10:2379
  - 10.0.0.11:2379
  nsServerAddress: 10.0.0.20:3930
