//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *MachineInfrastructureSpec) DeepCopyInto(out *MachineInfrastructureSpec) {
	*out = *in
	if in.SubnetIDs != nil {
		out.SubnetIDs = make([]string, len(in.SubnetIDs))
		copy(out.SubnetIDs, in.SubnetIDs)
	}
	if in.SecurityGroupIDs != nil {
		out.SecurityGroupIDs = make([]string, len(in.SecurityGroupIDs))
		copy(out.SecurityGroupIDs, in.SecurityGroupIDs)
	}
	if in.MinReplicas != nil {
		out.MinReplicas = new(int32)
		*out.MinReplicas = *in.MinReplicas
	}
	if in.MaxReplicas != nil {
		out.MaxReplicas = new(int32)
		*out.MaxReplicas = *in.MaxReplicas
	}
	if in.Tags != nil {
		out.Tags = make(map[string]string, len(in.Tags))
		for k, v := range in.Tags {
			out.Tags[k] = v
		}
	}
}

func (in *MachineInfrastructureSpec) DeepCopy() *MachineInfrastructureSpec {
	if in == nil {
		return nil
	}
	out := new(MachineInfrastructureSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CloudStatus) DeepCopyInto(out *CloudStatus) {
	*out = *in
}

func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

func (in *MachineBootstrapSpec) DeepCopyInto(out *MachineBootstrapSpec) {
	*out = *in
	in.Kubeconfig.DeepCopyInto(&out.Kubeconfig)
}

func (in *MachineBootstrapSpec) DeepCopy() *MachineBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(MachineBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KubeconfigBootstrapSpec) DeepCopyInto(out *KubeconfigBootstrapSpec) {
	*out = *in
	if in.RemoteRef != nil {
		out.RemoteRef = new(RemoteContentRef)
		*out.RemoteRef = *in.RemoteRef
	}
}

func (in *KubeconfigBootstrapSpec) DeepCopy() *KubeconfigBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(KubeconfigBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RemoteContentRef) DeepCopyInto(out *RemoteContentRef) {
	*out = *in
}

func (in *RemoteContentRef) DeepCopy() *RemoteContentRef {
	if in == nil {
		return nil
	}
	out := new(RemoteContentRef)
	in.DeepCopyInto(out)
	return out
}

func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
}

func (in *ResolvedLinkStatus) DeepCopyInto(out *ResolvedLinkStatus) {
	*out = *in
	if in.PDAddresses != nil {
		out.PDAddresses = make([]string, len(in.PDAddresses))
		copy(out.PDAddresses, in.PDAddresses)
	}
	if in.TLSSecretRef != nil {
		out.TLSSecretRef = new(corev1.LocalObjectReference)
		*out.TLSSecretRef = *in.TLSSecretRef
	}
}

func (in *ResolvedLinkStatus) DeepCopy() *ResolvedLinkStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedLinkStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TiDBInstanceLink) DeepCopyInto(out *TiDBInstanceLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TiDBInstanceLink) DeepCopy() *TiDBInstanceLink {
	if in == nil {
		return nil
	}
	out := new(TiDBInstanceLink)
	in.DeepCopyInto(out)
	return out
}

func (in *TiDBInstanceLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TiDBInstanceLinkList) DeepCopyInto(out *TiDBInstanceLinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TiDBInstanceLink, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *TiDBInstanceLinkList) DeepCopy() *TiDBInstanceLinkList {
	if in == nil {
		return nil
	}
	out := new(TiDBInstanceLinkList)
	in.DeepCopyInto(out)
	return out
}

func (in *TiDBInstanceLinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TiDBInstanceLinkSpec) DeepCopyInto(out *TiDBInstanceLinkSpec) {
	*out = *in
	in.MachineGroupRef.DeepCopyInto(&out.MachineGroupRef)
	if in.Port != nil {
		out.Port = new(int32)
		*out.Port = *in.Port
	}
	if in.PDAddresses != nil {
		out.PDAddresses = make([]string, len(in.PDAddresses))
		copy(out.PDAddresses, in.PDAddresses)
	}
	if in.TLSSecretRef != nil {
		out.TLSSecretRef = new(corev1.LocalObjectReference)
		*out.TLSSecretRef = *in.TLSSecretRef
	}
}

func (in *TiDBInstanceLinkSpec) DeepCopy() *TiDBInstanceLinkSpec {
	if in == nil {
		return nil
	}
	out := new(TiDBInstanceLinkSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TiDBInstanceLinkStatus) DeepCopyInto(out *TiDBInstanceLinkStatus) {
	*out = *in
	if in.AssignedPort != nil {
		out.AssignedPort = new(int32)
		*out.AssignedPort = *in.AssignedPort
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *TiDBInstanceLinkStatus) DeepCopy() *TiDBInstanceLinkStatus {
	if in == nil {
		return nil
	}
	out := new(TiDBInstanceLinkStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachine) DeepCopyInto(out *TiProxyMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TiProxyMachine) DeepCopy() *TiProxyMachine {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachine)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TiProxyMachineGroup) DeepCopyInto(out *TiProxyMachineGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TiProxyMachineGroup) DeepCopy() *TiProxyMachineGroup {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachineGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TiProxyMachineGroupList) DeepCopyInto(out *TiProxyMachineGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TiProxyMachineGroup, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *TiProxyMachineGroupList) DeepCopy() *TiProxyMachineGroupList {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachineGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TiProxyMachineGroupSpec) DeepCopyInto(out *TiProxyMachineGroupSpec) {
	*out = *in
	if in.Replicas != nil {
		out.Replicas = new(int32)
		*out.Replicas = *in.Replicas
	}
	if in.LinkSelector != nil {
		out.LinkSelector = new(metav1.LabelSelector)
		in.LinkSelector.DeepCopyInto(out.LinkSelector)
	}
	in.Infrastructure.DeepCopyInto(&out.Infrastructure)
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	in.TiProxy.DeepCopyInto(&out.TiProxy)
}

func (in *TiProxyMachineGroupSpec) DeepCopy() *TiProxyMachineGroupSpec {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachineGroupStatus) DeepCopyInto(out *TiProxyMachineGroupStatus) {
	*out = *in
	if in.AllocatedPorts != nil {
		out.AllocatedPorts = make(map[string]int32, len(in.AllocatedPorts))
		for k, v := range in.AllocatedPorts {
			out.AllocatedPorts[k] = v
		}
	}
	if in.ResolvedLinks != nil {
		out.ResolvedLinks = make([]ResolvedLinkStatus, len(in.ResolvedLinks))
		for i := range in.ResolvedLinks {
			in.ResolvedLinks[i].DeepCopyInto(&out.ResolvedLinks[i])
		}
	}
	in.Cloud.DeepCopyInto(&out.Cloud)
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *TiProxyMachineGroupStatus) DeepCopy() *TiProxyMachineGroupStatus {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachineList) DeepCopyInto(out *TiProxyMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TiProxyMachine, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *TiProxyMachineList) DeepCopy() *TiProxyMachineList {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineList)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TiProxyMachineSpec) DeepCopyInto(out *TiProxyMachineSpec) {
	*out = *in
	in.MachineGroupRef.DeepCopyInto(&out.MachineGroupRef)
}

func (in *TiProxyMachineSpec) DeepCopy() *TiProxyMachineSpec {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyMachineStatus) DeepCopyInto(out *TiProxyMachineStatus) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *TiProxyMachineStatus) DeepCopy() *TiProxyMachineStatus {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TiProxyRuntimeSpec) DeepCopyInto(out *TiProxyRuntimeSpec) {
	*out = *in
	if in.Config != nil {
		out.Config = new(runtime.RawExtension)
		in.Config.DeepCopyInto(out.Config)
	}
	if in.ExtraArgs != nil {
		out.ExtraArgs = make([]string, len(in.ExtraArgs))
		copy(out.ExtraArgs, in.ExtraArgs)
	}
}

func (in *TiProxyRuntimeSpec) DeepCopy() *TiProxyRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(TiProxyRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}
