//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStatus) DeepCopyInto(out *CloudStatus) {
	*out = *in
	if in.LoadBalancers != nil {
		in, out := &in.LoadBalancers, &out.LoadBalancers
		*out = make([]LoadBalancerCloudStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStatus.
func (in *CloudStatus) DeepCopy() *CloudStatus {
	if in == nil {
		return nil
	}
	out := new(CloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposureSpec) DeepCopyInto(out *ExposureSpec) {
	*out = *in
	if in.LoadBalancers != nil {
		in, out := &in.LoadBalancers, &out.LoadBalancers
		*out = make([]LoadBalancerExposureSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposureSpec.
func (in *ExposureSpec) DeepCopy() *ExposureSpec {
	if in == nil {
		return nil
	}
	out := new(ExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigBootstrapSpec) DeepCopyInto(out *KubeconfigBootstrapSpec) {
	*out = *in
	if in.RemoteRef != nil {
		in, out := &in.RemoteRef, &out.RemoteRef
		*out = new(RemoteContentRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigBootstrapSpec.
func (in *KubeconfigBootstrapSpec) DeepCopy() *KubeconfigBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(KubeconfigBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerCloudStatus) DeepCopyInto(out *LoadBalancerCloudStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerCloudStatus.
func (in *LoadBalancerCloudStatus) DeepCopy() *LoadBalancerCloudStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerCloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerExposureSpec) DeepCopyInto(out *LoadBalancerExposureSpec) {
	*out = *in
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerExposureSpec.
func (in *LoadBalancerExposureSpec) DeepCopy() *LoadBalancerExposureSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineBootstrapSpec) DeepCopyInto(out *MachineBootstrapSpec) {
	*out = *in
	in.Kubeconfig.DeepCopyInto(&out.Kubeconfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineBootstrapSpec.
func (in *MachineBootstrapSpec) DeepCopy() *MachineBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(MachineBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinePortCloudStatus) DeepCopyInto(out *MachinePortCloudStatus) {
	*out = *in
	if in.LoadBalancers != nil {
		in, out := &in.LoadBalancers, &out.LoadBalancers
		*out = make([]MachinePortLoadBalancerCloudStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinePortCloudStatus.
func (in *MachinePortCloudStatus) DeepCopy() *MachinePortCloudStatus {
	if in == nil {
		return nil
	}
	out := new(MachinePortCloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinePortLoadBalancerCloudStatus) DeepCopyInto(out *MachinePortLoadBalancerCloudStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinePortLoadBalancerCloudStatus.
func (in *MachinePortLoadBalancerCloudStatus) DeepCopy() *MachinePortLoadBalancerCloudStatus {
	if in == nil {
		return nil
	}
	out := new(MachinePortLoadBalancerCloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpec) DeepCopyInto(out *MachineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpec.
func (in *MachineSpec) DeepCopy() *MachineSpec {
	if in == nil {
		return nil
	}
	out := new(MachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineStatus) DeepCopyInto(out *MachineStatus) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineStatus.
func (in *MachineStatus) DeepCopy() *MachineStatus {
	if in == nil {
		return nil
	}
	out := new(MachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementSpec) DeepCopyInto(out *PlacementSpec) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementSpec.
func (in *PlacementSpec) DeepCopy() *PlacementSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRange.
func (in *PortRange) DeepCopy() *PortRange {
	if in == nil {
		return nil
	}
	out := new(PortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteContentRef) DeepCopyInto(out *RemoteContentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteContentRef.
func (in *RemoteContentRef) DeepCopy() *RemoteContentRef {
	if in == nil {
		return nil
	}
	out := new(RemoteContentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedLinkStatus) DeepCopyInto(out *ResolvedLinkStatus) {
	*out = *in
	if in.PDAddresses != nil {
		in, out := &in.PDAddresses, &out.PDAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedLinkStatus.
func (in *ResolvedLinkStatus) DeepCopy() *ResolvedLinkStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedLinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceNamesSpec) DeepCopyInto(out *ResourceNamesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceNamesSpec.
func (in *ResourceNamesSpec) DeepCopy() *ResourceNamesSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceNamesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSpec.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiDBResourcePoolLink) DeepCopyInto(out *TiDBResourcePoolLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiDBResourcePoolLink.
func (in *TiDBResourcePoolLink) DeepCopy() *TiDBResourcePoolLink {
	if in == nil {
		return nil
	}
	out := new(TiDBResourcePoolLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiDBResourcePoolLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiDBResourcePoolLinkList) DeepCopyInto(out *TiDBResourcePoolLinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TiDBResourcePoolLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiDBResourcePoolLinkList.
func (in *TiDBResourcePoolLinkList) DeepCopy() *TiDBResourcePoolLinkList {
	if in == nil {
		return nil
	}
	out := new(TiDBResourcePoolLinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiDBResourcePoolLinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiDBResourcePoolLinkSpec) DeepCopyInto(out *TiDBResourcePoolLinkSpec) {
	*out = *in
	out.MachineGroupRef = in.MachineGroupRef
	if in.PDAddresses != nil {
		in, out := &in.PDAddresses, &out.PDAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiDBResourcePoolLinkSpec.
func (in *TiDBResourcePoolLinkSpec) DeepCopy() *TiDBResourcePoolLinkSpec {
	if in == nil {
		return nil
	}
	out := new(TiDBResourcePoolLinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiDBResourcePoolLinkStatus) DeepCopyInto(out *TiDBResourcePoolLinkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiDBResourcePoolLinkStatus.
func (in *TiDBResourcePoolLinkStatus) DeepCopy() *TiDBResourcePoolLinkStatus {
	if in == nil {
		return nil
	}
	out := new(TiDBResourcePoolLinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachineGroup) DeepCopyInto(out *TiProxyMachineGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachineGroup.
func (in *TiProxyMachineGroup) DeepCopy() *TiProxyMachineGroup {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiProxyMachineGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachineGroupList) DeepCopyInto(out *TiProxyMachineGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TiProxyMachineGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachineGroupList.
func (in *TiProxyMachineGroupList) DeepCopy() *TiProxyMachineGroupList {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiProxyMachineGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachineGroupSpec) DeepCopyInto(out *TiProxyMachineGroupSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Scaling.DeepCopyInto(&out.Scaling)
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(ObjectReference)
		**out = **in
	}
	out.PortRange = in.PortRange
	if in.LinkSelector != nil {
		in, out := &in.LinkSelector, &out.LinkSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Exposure.DeepCopyInto(&out.Exposure)
	in.Placement.DeepCopyInto(&out.Placement)
	out.ResourceNames = in.ResourceNames
	out.Machine = in.Machine
	in.Network.DeepCopyInto(&out.Network)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	in.TiProxy.DeepCopyInto(&out.TiProxy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachineGroupSpec.
func (in *TiProxyMachineGroupSpec) DeepCopy() *TiProxyMachineGroupSpec {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachineGroupStatus) DeepCopyInto(out *TiProxyMachineGroupStatus) {
	*out = *in
	if in.AllocatedPorts != nil {
		in, out := &in.AllocatedPorts, &out.AllocatedPorts
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResolvedLinks != nil {
		in, out := &in.ResolvedLinks, &out.ResolvedLinks
		*out = make([]ResolvedLinkStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Machines != nil {
		in, out := &in.Machines, &out.Machines
		*out = make(map[string]MachineStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Cloud.DeepCopyInto(&out.Cloud)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachineGroupStatus.
func (in *TiProxyMachineGroupStatus) DeepCopy() *TiProxyMachineGroupStatus {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachineGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachinePort) DeepCopyInto(out *TiProxyMachinePort) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachinePort.
func (in *TiProxyMachinePort) DeepCopy() *TiProxyMachinePort {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachinePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiProxyMachinePort) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachinePortList) DeepCopyInto(out *TiProxyMachinePortList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TiProxyMachinePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachinePortList.
func (in *TiProxyMachinePortList) DeepCopy() *TiProxyMachinePortList {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachinePortList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiProxyMachinePortList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachinePortSpec) DeepCopyInto(out *TiProxyMachinePortSpec) {
	*out = *in
	out.MachineGroupRef = in.MachineGroupRef
	if in.RequestedPort != nil {
		in, out := &in.RequestedPort, &out.RequestedPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachinePortSpec.
func (in *TiProxyMachinePortSpec) DeepCopy() *TiProxyMachinePortSpec {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachinePortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyMachinePortStatus) DeepCopyInto(out *TiProxyMachinePortStatus) {
	*out = *in
	if in.AssignedPort != nil {
		in, out := &in.AssignedPort, &out.AssignedPort
		*out = new(int32)
		**out = **in
	}
	in.Cloud.DeepCopyInto(&out.Cloud)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyMachinePortStatus.
func (in *TiProxyMachinePortStatus) DeepCopy() *TiProxyMachinePortStatus {
	if in == nil {
		return nil
	}
	out := new(TiProxyMachinePortStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiProxyRuntimeSpec) DeepCopyInto(out *TiProxyRuntimeSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiProxyRuntimeSpec.
func (in *TiProxyRuntimeSpec) DeepCopy() *TiProxyRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(TiProxyRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}
